version: '3.3'
services:
    elasticsearch:
        container_name: elasticsearch
        ports:
            - '9200:9200'
        environment:
            - discovery.type=single-node
            - 'ES_JAVA_OPTS=-Xms96m -Xmx96m'
        image: 'elasticsearch:7.10.1'