---

# Enable discovery type of single-node
singleNode: true

# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx47m -Xms47m"

image: docker.elastic.co/elasticsearch/elasticsearch-oss

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "250Mi"
    cpu: "800m"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
